name: ccagg
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-learn<1.6
  - pandas
  - matplotlib
  - seaborn
  - joblib
  - tqdm
  - pip
  - pip:
      - cca-zoo>=2.6,<3.0
      - -e .
